name: My workflow

on: push

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to yellow-trade.surge.sh
    
        with:
          domain: 'yellow-trade.surge.sh'
          project: 'C:\Users\PC\OneDrive\Desktop\bootcamp\bootcamp1\build\'
          token: ${{ secrets.surge_token }}